client_id = "9425bfa0f620a9a814417e7ccba31502"
name = "RedirectMapperLite"
application_url = "https://qorve-1.duckdns.org"
embedded = true

[access_scopes]
scopes = "read_products,write_products,write_online_store_navigation"

[auth]
redirect_urls = [ "https://qorve-1.duckdns.org/auth/callback" ]

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/compliance"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[build]
automatically_update_urls_on_dev = true
